# permissions for end users to view doclingserves.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: docling-operator
    app.kubernetes.io/managed-by: kustomize
  name: doclingserve-viewer-role
rules:
- apiGroups:
  - docling.github.io
  resources:
  - doclingserves
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - docling.github.io
  resources:
  - doclingserves/status
  verbs:
  - get
