apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: docling-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DoclingServ is the Schema for the doclingservs API
      displayName: Docling Serv
      kind: DoclingServ
      name: doclingservs.docling.github.io
      version: v1alpha1
  description: docling-operator provisions an instance of the docling api service.
  displayName: docling-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - document
  - processing
  links:
  - name: Docling Operator
    url: https://docling-operator.domain
  maturity: alpha
  provider:
    name: opdev
    url: https://docling-project.github.io/docling/
  version: 0.0.0
