apiVersion: docling.github.io/v1alpha1
kind: DoclingServe
metadata:
  labels:
    app.kubernetes.io/name: docling-operator
    app.kubernetes.io/managed-by: kustomize
  name: doclingserve-sample
spec:
  apiServer:
    image: "quay.io/docling-project/docling-serve:latest"
    enableUI: false
    instances: 1
  engine:
    local:
      numWorkers: 2
  route:
    enabled: false
